name: Mirror to Bitbucket

on:
  push:
    branches:
      - master  # Change to 'main' if that's your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up authentication for Bitbucket
      run: |
        echo "machine bitbucket.org" > ~/.netrc
        echo "login $BITBUCKET_USERNAME" >> ~/.netrc
        echo "password $BITBUCKET_APP_PASS" >> ~/.netrc

    - name: Push to Bitbucket
      run: |
        git remote add bitbucket https://bitbucket.org/tg_practice/dialy_commit.git
        git push bitbucket --mirror
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_APP_PASS: ${{ secrets.BITBUCKET_APP_PASS }}