name: Mirror to Bitbucket

on:
  push:
    branches:
      - master  # Change if your main branch is called "main"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to Bitbucket
      run: |
        git remote add bitbucket https://$thejaswi_govinda_b_s:$ATBBr67qVPzJ3G6mHj8QJQAYBqQM5965EE9E@bitbucket.org/tg_practice/tg_practice.git
        git push bitbucket --mirror
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_APP_PASS: ${{ secrets.BITBUCKET_APP_PASS }}
